services:
  - type: web
    name: mi-radio-online
    runtime: docker
    plan: free
    envVars:
      - key: 6fd9e8ea9ec3a18abadb6af33c6d7845
        generateValue: true
      - key: b6e5a092c78e5aabcae387bbf95f915a
        generateValue: true
      - key: 3e0457a323fe43e917606a9d7096cfe6

        generateValue: true
