services:
  - type: web
    name: radio-icecast
    runtime: docker
    plan: free
    # PUERTO CLAVE: nginx escucha aquí
    envVars:
      - key: PORT
        value: 8080  # ← nginx usa este puerto
      - key: SOURCE_PASS
        value: 6fd9e8ea9ec3a18abadb6af33c6d7845
      - key: RELAY_PASS
        value: b6e5a092c78e5aabcae387bbf95f915a
      - key: ADMIN_PASS
        value: 3e0457a323fe43e917606a9d7096cfe6
